### PR TITLE
VaryByHeader & VaryByParam Wildcard not working.

### PR DESCRIPTION
**Pull request by oguzhankahyaoglu**

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by oguzhankahyaoglu** [comment]
Can you release a new version containing this fix since I needed for it :)

**Comment by matias-milletari** [comment]
Hi @madskristensen, 

Do you have an ETA on the release of a new version with this fix? I am also having the same issue.

Thanks!

**Comment by madskristensen** [comment]
@matias-milletari thanks for the notch. I just kicked off a release build that will automatically publish to NuGet upon completion.

**Comment by madskristensen** [comment]
It's now released and available on NuGet

**Comment by matias-milletari** [comment]
@madskristensen Thanks for your quick response! I've already downloaded and tried setting the `VaryByParam` parameter with the wildcard (*), but it's not working. I did this through a Profile in Startup.cs and as a attribute parameter too, but neither worked. I'm using this attribute

`[OutputCache(Duration = 600, VaryByParam = "*")]`

Maybe I'm doing something wrong? I want the cache to vary for all query parameters.

**Pull request merged**
